### ISSUE TITLE
BCC and CC not working

### ISSUE THREAD

**Issue by vyshnavi-samudrala** [pepipost/pepipost-sdk-nodejs#1]
I've tried adding BCC and CC to the email_details and recipients. But it is breaking the code. Where do I add the BCC and CC emails?

**Comment by tteke** [comment]
I think [this](https://developers.pepipost.com/api/personalizations) might help

**Comment by geniusdibya** [comment]
We have released the latest version of our NodeJS SDK v2.5.2, here this issue is addressed. Also, here is an example of how to use Bcc and Cc in an email sending API: [https://github.com/pepipost/pepipost-sdk-nodejs#usage](https://github.com/pepipost/pepipost-sdk-nodejs#usage)
